export enum EXEPTION {
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  AUTHORISATION_ERROR = "AUTHORISATION_ERROR",
  NOT_FOUND_EXEPTION = "NOT_FOUND_EXEPTION",
  SERVER_ERROR = "SERVER_ERROR",
  UNHANDLED_ERROR = "UNHANDLED_ERROR",
}
